### ISSUE TITLE
Why can't we use instance variables for BlockWhere?

### ISSUE THREAD

**Issue by gentaro-sakamoto** [techscore/activerecord-blockwhere#3]
Hi, thank you for your simple but convenient gem. I have a question. Why can't we use instance variables for BlockWhere? What is the essential problem? 

```
# in action method
def index
  # you can use controller's method in the block. ex: params,request,etc..
  # but cannot use instance variables.
  @person = Person.where { id.eq(params[:id]) }.first
end
```

**Comment by yuki-teraoka** [comment]
Thank you for the question.
Please tell us the Rails version and error stack trace that your are using.
If so, I might be able to answer your question.

**Comment by yuki-teraoka** [comment]
Excuse me. I was misunderstood your question.
can not use an instance variable, because BlockWhere have delegate method calls using method_missing in the block to block definition original instance.
Does not exist instance_variable_missing in Ruby.
